#!/bin/sh

# Stop immediately on error
set -e

# Double-check linting on all files
npx eslint --fix . --resolve-plugins-relative-to .
# Ensure tests pass and coverage is met before push
npx jest --colors
